### ISSUE TITLE
Unable to set `allow_votes` to false

### ISSUE THREAD

**Issue by jakipatryk** [bonustrack/steemconnect#292]
When I try to set `allow_votes` in `comment_options` to false, SteemConnect responds with a status 500:
```
{
    "error": "server_error",
    "error_description": "Missing Posting Authority <username>"
}
```

It used to work fine (about 2-3 months ago).

**Comment by jakipatryk** [comment]
Nevermind, I'm getting also getting the error when I sign transactions locally, it's not the SteemConnect problem.

**Comment by jakipatryk** [comment]
The problem is caused by `api.steemit.com` node, I managed to broadcast the `comment_option` with `allow_votes` set to false via Gandalf's node.

I'll keep this issue open.

**Comment by ajayyy** [comment]
Does steemconnect only connect with api.steemit.com

**Comment by MSiccDev** [comment]
I have the same problem using SteemConnect API, which by default goes to api.steemit.com.
