### ISSUE TITLE
/sign/delegateVestingShares visual error

### ISSUE THREAD

**Issue by selfisekai** [bonustrack/steemconnect#301]
SteemConnect doesn't display minimal delegation properly
![obraz](https://user-images.githubusercontent.com/11798442/42391877-0ea2449e-8151-11e8-9147-e975caa4f3be.png)

**Comment by Sekhmet** [comment]
Longer error:
![image](https://user-images.githubusercontent.com/1968722/42445030-15e1b334-8372-11e8-9375-50acff7fa38d.png)

**Comment by bonustrack** [comment]
Closing this issue, it's not relevant anymore on steemconnect latest version.
