### ISSUE TITLE
Steemconnect v2 - Revoking all token is not working

### ISSUE THREAD

**Issue by sourovafrin** [bonustrack/steemconnect#308]
#### Expected behavior

If user click on **Revoke tokens** steemconnect should revoke all OAuth tokens if user wants to invalidate the access of any existing token Steem apps.

#### Actual behavior

When user click on **Revoke tokens** steemconnect ask for confirmation and after clicking on yes it loads for a while and shows below message-
>Success
Tokens have been successfully deleted

But it do not revoke any token.

#### How to reproduce

- Visit this link- https://v2.steemconnect.com/login and sign in you steemit account.

- Now go on authorized page or just click [here](https://v2.steemconnect.com/apps/authorized)

- Below of the page you will see **Revoke tokens** button, click on it

- After clicking it will ask for confirmation. Click on yes to confirm

- It will load for a while and will show a success message.

- But You will see that it no token was revoked even there is no block for this on steemd.

* Browser version: Chrome Version 67.0.3396.99 (Official Build) (64-bit)

* Operating system: Windows 8.1

#### Recording Of The Bug
https://youtu.be/KqcLE9BHDR8

**Comment by bonustrack** [comment]
Closing this issue, it's not relevant anymore on steemconnect latest version.
