### ISSUE TITLE
Steemconnect v0.1.0 - Challenge Route crashes Steemconnect

### ISSUE THREAD

**Issue by wehmoen** [bonustrack/steemconnect#310]
The route `/api/login/challenge` is used during the login process and expects the parameters `username` and `role`

#### Expected behavior
When one of those two parameters is not set or empty the page should display a proper JSON response with an error message indicating which parameter is invalid or missing.

#### Actual behavior
However when one of those parameters is not set or empty the app crashes and an error page from Heroku is show.

![](https://cdn.steemitimages.com/DQmX5WXAjf59qWtzSszNnbh4nN6dQYzwYT5zP4xUpmyKaZ5/image.png)

#### How to reproduce
[Just click this link](https://v2.steemconnect.com/api/login/challenge?username=&role=owner)

* Browser/App version: Chrome/67.0.3396.99
* Operating system: Windows 10

#### Recording Of The Bug
A recording of the bug can be found in my GDrive: 
https://drive.google.com/open?id=1IPtk9oP6199vb4PYvEch3LNxDR898xr1

#### GitHub Account
https://github.com/wehmoen

**Comment by bonustrack** [comment]
Good catch @wehmoen, do you want to do a PR to fix this?

**Comment by asgarth** [comment]
Any news or ETA to have this fixed?

**Comment by bonustrack** [comment]
Closing this issue, it's not relevant anymore on steemconnect latest version.
