### ISSUE TITLE
Unable to recover account

### ISSUE THREAD

**Issue by stm12** [bonustrack/steemconnect#328]
I am getting "Error found: Recent authority not found in authority history."

https://steemconnect.com/accounts/recover

**Comment by bonustrack** [comment]
Did the account you trying to recover have updated password less than 30 days ago?

**Comment by stm12** [comment]
> Did the account you trying to recover have updated password less than 30 days ago?

I've just tested my recent password on steemit.com recovery tool and it works. But my recovery account is not steemit, this account has been created via steemconnect and I am still getting "Recent authority not found in authority history." error on steemconnect recovery page.

**Comment by bonustrack** [comment]
This feature isn't supported anymore
