### ISSUE TITLE
Oops, something went wrong. Here is the error message:  "Account: XYZ has 32055662834 RC, needs 435422517 RC. Please wait to transact, or power up STEEM."

### ISSUE THREAD

**Issue by rixosyed** [bonustrack/steemconnect#390]
Oops, something went wrong. Here is the error message: 
"Account: itsolutions has 32055662834 RC, needs 435422517 RC. Please wait to transact, or power up STEEM."

Please Help

**Comment by bonustrack** [comment]
As said in the error, it seem that your account don't have enough Steem Power to transact, you either need to wait or power up.
