### ISSUE TITLE
2 problems of custom_json with active key

### ISSUE THREAD

**Issue by economicstudio** [bonustrack/steemconnect#394]
### Expected behavior

custom_json operations should support active key

### Actual behavior
1. The prompt says `posting key` also works, which is not true.

![](https://user-images.githubusercontent.com/38183982/58387608-3001dc00-8009-11e9-8e6e-41e5963adff2.png)

2. Even active key doesn't work with both SC2 & SC3
![](https://user-images.githubusercontent.com/38183982/58387595-ff21a700-8008-11e9-9c09-e20805265fdb.png)
> SC2

![](https://user-images.githubusercontent.com/38183982/58387597-08ab0f00-8009-11e9-94ef-52cb2211fa5e.png)
> SC3

Based on the error message it seems SC is trying to cast querystring to array and it's not working.

### Steps to reproduce the behavior
Both SC2 & SC3 don't work

![](https://user-images.githubusercontent.com/38183982/58387582-b8cc4800-8008-11e9-81de-ecc32eb474c5.png)

https://app.steemconnect.com/sign/custom-json?required_auths=%5B%22blockchainstudio%22%5D&id=test&json=%7B%22k1%22%3A%20%22v1%22%2C%20%22k2%22%3A%202%7D
> SC2

https://beta.steemconnect.com/sign/custom-json?required_auths=%5B%22blockchainstudio%22%5D&id=test&json=%7B%22k1%22%3A%20%22v1%22%2C%20%22k2%22%3A%202%7D
> SC3

custom_json with posting key works well.

**Comment by bonustrack** [comment]
You need to add the parameter "&authority=active" on the signing url to force user to sign it with his active key.
