### ISSUE TITLE
Steemconnect forced beta

### ISSUE THREAD

**Issue by shellaaaron** [bonustrack/steemconnect#412]
### Expected behavior
normally login without giving full access to steem network, even so, the beta or not I do not want to give full access.

### Actual behavior
go to the beta website without even signup for the beta when using it. when going to steemconnect.com it simply redirects me to beta.steemconnect.com

### Steps to reproduce the behavior
tried to use a differnet browser with the same issue.

**Comment by bonustrack** [comment]
What do you mean by "giving full access to steem network", you mean you dont want to delegate your posting authority to an app?

**Comment by kirkins** [comment]
Is it possible to unauthorize on the beta? I have some apps that can like on my behalf I want to remove.

**Comment by bonustrack** [comment]
@kirkins You can go here to see authorized accounts and to unauthorize some https://beta.steemconnect.com/auths

**Comment by shellaaaron** [comment]
How to sign out of the beta and use a stable version?
