### ISSUE TITLE
App says key is invalid.  

### ISSUE THREAD

**Issue by fionasfavourites** [bonustrack/steemconnect#415]
Hi
I have the extension which works.  but if I log in, e.g. to the dpoll, it tells me the key is invalid.  Please advise.

**Comment by bonustrack** [comment]
Do you still having that issue?

**Comment by fionasfavourites** [comment]
Thank, no, all sorted.

-- 
Fiona Cameron-Brown
The Sandbag House
McGregor
Tel: +27 +23 625 1450
WhatsApp: 082 924 8997
http://fionasfavourites.net/
