### ISSUE TITLE
cannot login from another computer

### ISSUE THREAD

**Issue by economicstudio** [bonustrack/steemconnect#416]
### Expected behavior
Should be able to login from another computer

### Actual behavior
For instance, https://busy.org
I can login from one computer, but not with others.

I've already deleted cookies. didn't work.

### Steps to reproduce the behavior
- just log in from another computer to, for instance, https://busy.org

![](https://user-images.githubusercontent.com/38183982/61824428-df1a3280-ae55-11e9-9245-b09cdf92f189.png)

**Comment by bonustrack** [comment]
Are you using steemconnect website or desktop / chrome app? If it's not the website, which version are you using (see in "About" section)?.

**Comment by economicstudio** [comment]
It's desktop Version: 0.1.2

It seems 0.1.3 was released two weeks ago, I'll test with it and let you again. Thanks.

**Comment by economicstudio** [comment]
Working with 0.1.3!

It'd be great if there is an auto update or update notification. Thanks.
