### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by varioso** [bonustrack/steemconnect#417]
### Expected behavior
As others have stated previously.

I have a dApp using SC which was working normally up until a few weeks ago, i.e. users were able to log in normally with any Steem account.

### Actual behavior

In recent weeks, however, SC would not log me in. It would accept my credentials, go through all the steps - login, key, etc. and then redirect me to the homepage again. I guess I need to update some of the vars in the configuration. Would appreciate any tips here.

I've added the app to SC dashboard with the right callback url, etc.

### Steps to reproduce the behavior

Just log in as I would normally do to into the dApp.

**Comment by bonustrack** [comment]
Which dapp isnt working?

**Comment by varioso** [comment]
I apologize, the issue was due to the deprecated metadata feature which you guys have taken the time to blog about well in advance here:
https://steemit.com/steemconnect/@fabien/steemconnect-deprecation-notice-for-the-metadata-feature

My bad. Thanks for your support.
