### ISSUE TITLE
Oops, something went wrong. Here is the error message: "Cannot convert string to bool (only "true" or "false" can be converted)" when voting by witness

### ISSUE THREAD

**Issue by marjuanm** [bonustrack/steemconnect#425]
Hello:

  I reported this error at https://github.com/steemit/steem/issues/3463 but they recommended that I report it better in this area. When I want to vote for a witness on Steemit this error message appears:
![63025203-51d36800-be6e-11e9-9090-d27f4d84959b](https://user-images.githubusercontent.com/30614131/64346844-81cae280-cfb8-11e9-87ca-303ee6cc0847.png)
Greetings.

**Comment by bonustrack** [comment]
The url is wrong, it should be ending with `...&approve=true`, another option is to remove the param "approve", by default it will be converted to true.

**Comment by marjuanm** [comment]
then replace &approve=1 with &approve=true?

**Comment by bonustrack** [comment]
@marjuanm We made a change, now both `&approve=true` and `&approve=1` are working.

**Comment by marjuanm** [comment]
Thank you, but now this error message is displayed.
![Screenshot_1](https://user-images.githubusercontent.com/30614131/64978846-10264a80-d87c-11e9-9cd8-42cd2bd5880c.png)

**Comment by bonustrack** [comment]
@marjuanm this is a different error, make sure your local clock is properly sync.
