### ISSUE TITLE
How can I login the dashboard?

### ISSUE THREAD

**Issue by ety001** [bonustrack/steemconnect#427]
I registered app account ([steemeditor](https://steemd.com/@steemeditor)) on [https://v2.steemconnect.com/](https://v2.steemconnect.com/). And I don't have [steemeditor](https://steemd.com/@steemeditor)'s private key. 

So how can I login  [steemeditor](https://steemd.com/@steemeditor) on Beta version?

**Comment by bonustrack** [comment]
@ety001 The app account active and posting keys are the same as the account you used to create the app on the steemconnect v2 which is "@ety001"

**Comment by ety001** [comment]
> @ety001 The app account active and posting keys are the same as the account you used to create the app on the steemconnect v2 which is "@ety001"

OK, thank you. That's a weird design.
